'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Calendar, MapPin, Car, DollarSign, Users, Clock, Navigation, Bell } from 'lucide-react'
import { toast } from 'sonner'
import ProfileCard from './components/ProfileCard'
import ScheduleView from './components/ScheduleView'
import BookingRequests from './components/BookingRequests'
import VehicleStatus from './components/VehicleStatus'
import RouteMap from './components/RouteMap'
import Earnings from './components/Earnings'