"""update models to include a trips model and remove parents model

Revision ID: 26219806201a
Revises: 5392a2e98351
Create Date: 2026-01-29 23:10:19.488538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26219806201a'
down_revision = '5392a2e98351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('service_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trip_date', sa.DateTime(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('actual_pickup_time', sa.DateTime(), nullable=True),
    sa.Column('actual_dropoff_time', sa.DateTime(), nullable=True),
    sa.Column('driver_notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seats_booked', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('service_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('days_of_week', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('days_of_week')
        batch_op.drop_column('service_type')
        batch_op.drop_column('seats_booked')

    op.drop_table('trips')
    # ### end Alembic commands ###
