"""fix relationships

Revision ID: 4138e0b269ee
Revises: 214c019b7302
Create Date: 2026-02-04 22:39:17.342232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4138e0b269ee'
down_revision = '214c019b7302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('days_of_week',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('days_of_week',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('route_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
