"""increases character limits

Revision ID: 59e6d8443989
Revises: 61ea42c5db64
Create Date: 2026-02-11 10:41:47.632128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e6d8443989'
down_revision = '61ea42c5db64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_locations', schema=None) as batch_op:
        batch_op.alter_column('gps_coordinates',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('starting_point_gps',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('ending_point_gps',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('school_locations', schema=None) as batch_op:
        batch_op.alter_column('gps_coordinates',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('school_locations', schema=None) as batch_op:
        batch_op.alter_column('gps_coordinates',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('ending_point_gps',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('starting_point_gps',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('pickup_locations', schema=None) as batch_op:
        batch_op.alter_column('gps_coordinates',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
