"""changed column datetime to date

Revision ID: ebf66891e18c
Revises: 26219806201a
Create Date: 2026-01-30 18:05:08.662222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf66891e18c'
down_revision = '26219806201a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('service_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('trip_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('pickup_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('driver_notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('driver_notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('pickup_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('trip_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('service_time',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
